parameters:
    zamat_oauth2.server.class: OAuth2\Server
services:
    zamat_oauth2.request:
        class: Zamat\OAuth2\HttpFoundation\Request
    zamat_oauth2.response:
        class: Zamat\OAuth2\HttpFoundation\Response 
    zamat_oauth2.server:
        class: Zamat\OAuth2\Server\OAuth2
        arguments: []

        
        
        
