parameters:
    zamat_client_parameters:
        authorize_uri : "%zamat_oauth2_server.authorize_uri%"   
        token_uri : "%zamat_oauth2_server.token_uri%"   
        verify_uri : "%zamat_oauth2_server.verify_uri%"   
services:
    # security 
    oauth.security.authentication.client.parameters:
        class: Zamat\OAuth2\Client\OAuthClientParameters
        
    oauth.security.authentication.client:
        class: Zamat\OAuth2\Client\OAuthClient
        arguments: ["%zamat_client_parameters%"]
      
    oauth.security.user.provider:
        class: Zamat\OAuth2\Security\User\OAuth2UserProvider
        arguments: ["@oauth.security.authentication.client"]

    oauth.security.authentication.provider:
        class: Zamat\OAuth2\Security\Authentication\Provider\OAuth2Provider
        arguments: ["@oauth.security.user.provider"]
        public: false
        abstract : true
       
    oauth.security.authentication.listener:
        class: Zamat\OAuth2\Security\Authentication\Firewall\OAuth2Listener
        parent: security.authentication.listener.abstract
        public: false
        abstract : true

    oauth.client.security.entry_point:
        class: Zamat\OAuth2\Security\EntryPoint\OAuth2AuthorizationCodeEntryPoint
        arguments: ["%zamat_client_parameters%"]
        public: false    