Zamat\Bundle\OAuth2Bundle\Entity\RefreshToken:
    type: entity
    repositoryClass: Zamat\Bundle\OAuth2Bundle\Entity\Repository\RefreshTokenRepository  
    table: zamat_oauth_refresh_token
    id:
        token:
            type:       string
            length:     40
    fields:
        expires:
            type:       datetime
        scope:
            type:       string
            length:     255
            nullable:   true
    manyToOne:
      client:
        targetEntity: \Zamat\Bundle\OAuth2Bundle\Entity\Client
        joinColumn:
          name: client_id
          referencedColumnName: client_id
          onDelete: CASCADE
          onUpdate: CASCADE
      user:
        targetEntity: \Zamat\Bundle\SecurityBundle\Entity\EntityUser
        joinColumn:
          name: user_id
          referencedColumnName: id
          nullable: true
          onDelete: CASCADE
          onUpdate: CASCADE        
    lifecycleCallbacks: {  }
