Zamat\Bundle\OAuth2Bundle\Entity\Scope:
    type: entity
    table: zamat_oauth_scope
    id:
        scope:
            type:       string
            length:     255
    fields:
        description:
            type:       string
            length:     255
    lifecycleCallbacks: {  }
